-- treehole db init script
-- db create
CREATE DATABASE IF NOT EXISTS treehole
-- table create
create table IF NOT EXISTS admin(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,username VARCHAR(20) NOT NULL,password VARCHAR(50) NOT NULL )
CREATE TABLE IF NOT EXISTS bloginfo (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,name VARCHAR (50) NOT NULL,url VARCHAR (50),desc TEXT (500))
CREATE TABLE IF NOT EXISTS installinfo (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, idate VARCHAR (20) NOT NULL,iosname VARCHAR (20),iosdesktop  VARCHAR (20),ilocal VARCHAR (50),ibower VARCHAR (50),ioscpu VARCHAR (20),ijdkversion VARCHAR (20))
CREATE TABLE IF NOT EXISTS kind (id   INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, name VARCHAR (20) NOT NULL UNIQUE)
CREATE TABLE IF NOT EXISTS article (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, title VARCHAR (20) NOT NULL UNIQUE, subpath VARCHAR (100),tags VARCHAR (200),intro VARCHAR (500), introhtml VARCHAR (5000), article VARCHAR (5000),articlehtml VARCHAR (5000),kind NOT NULL,usecommont  VARCHAR (10) NOT NULL,flag INTEGER NOT NULL DEFAULT (0), date VARCHAR (20) NOT NULL DEFAULT (datetime()))
CREATE TABLE IF NOT EXISTS files ( id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (100) NOT NULL, path VARCHAR (200) NOT NULL, alias VARCHAR (50)  NOT NULL, contenttype VARCHAR (20))
