-- treehole db init script
-- db create
CREATE DATABASE IF NOT EXISTS treehole
-- table create
create table IF NOT EXISTS admin(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,username VARCHAR(20) NOT NULL,password VARCHAR(50) NOT NULL )
CREATE TABLE IF NOT EXISTS bloginfo (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,name VARCHAR (50) NOT NULL,url VARCHAR (50),desc TEXT (500))
CREATE TABLE installinfo (id INTEGER PRIMARY KEY UNIQUE NOT NULL AUTOINCREMENT, idate VARCHAR (20) NOT NULL,iosname VARCHAR (20),iosdesktop  VARCHAR (20),ilocal VARCHAR (50),ibower VARCHAR (50),ioscpu VARCHAR (20),ijdkversion VARCHAR (20))
CREATE TABLE kind (id   INTEGER PRIMARY KEY UNIQUE NOT NULL AUTOINCREMENT, name VARCHAR (20) NOT NULL UNIQUE)
CREATE TABLE article (id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, title VARCHAR (20) NOT NULL UNIQUE, incro VARCHAR (500), content VARCHAR (5000), tags VARCHAR (200), kindid INTEGER NOT NULL, usecommont INTEGER NOT NULL)
CREATE TABLE files ( id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (100) NOT NULL, path VARCHAR (200) NOT NULL, alias VARCHAR (50)  NOT NULL, contenttype VARCHAR (20))
