-- treehole db init script
-- db create
CREATE DATABASE IF NOT EXISTS treehole
-- table create
create table IF NOT EXISTS admin(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,username VARCHAR(20) NOT NULL,password VARCHAR(50) NOT NULL )
CREATE TABLE IF NOT EXISTS bloginfo (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,name VARCHAR (50) NOT NULL,url VARCHAR (50),desc TEXT (500))
